{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-cloud.fullname" . }}-config
  labels:
    {{- include "ai-cloud.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  ENVIRONMENT: {{ .Values.global.environment | quote }}
{{- end }}

